# This file is partially generated by AI.
set -e  # 遇到错误立即退出

# 颜色输出 (仅用于美化)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# 读取版本号
if [ ! -f VERSION ]; then
    echo -e "${RED}错误: VERSION 文件不存在${NC}"
    exit 1
fi
VERSION=$(cat VERSION | tr -d ' \t\n\r')
echo -e "${GREEN}版本号: ${VERSION}${NC}"

# 定义包导入路径 (用于 -ldflags)
PKG_VERSION="github.com/fltLi/webgal-snapshot/pkg/version"

# 1. 整理依赖
echo -e "${YELLOW}▶ 整理 Go 模块依赖...${NC}"
go mod tidy

# 2. 下载依赖
echo -e "${YELLOW}▶ 下载 Go 模块依赖...${NC}"
go mod download

# 3. 定义构建函数
build() {
    local GOOS=$1
    local GOARCH=$2
    local SUFFIX=$3
    local BINARY="webgal-snapshot-${VERSION}-${GOOS}-${GOARCH}${SUFFIX}"

    echo -e "${YELLOW}▶ 构建 ${BINARY} ...${NC}"
    env GOOS=$GOOS GOARCH=$GOARCH \
        go build -ldflags="-X ${PKG_VERSION}.Version=${VERSION}" \
        -o "$BINARY" ./cmd/webgal-snapshot
    echo -e "${GREEN}✅ 完成: ${BINARY}${NC}"
}

# 4. 构建各个平台
build "darwin" "arm64" ""      # macOS Apple Silicon
build "darwin" "amd64" ""      # macOS Intel
build "windows" "amd64" ".exe" # Windows 64-bit

echo -e "${GREEN}✅ 所有发布包构建完成！${NC}"
ls -lh webgal-snapshot-${VERSION}-*
